"""empty message

Revision ID: 5ad3937ac983
Revises: c5f8ca424772
Create Date: 2024-05-12 11:47:13.090543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5ad3937ac983'
down_revision = 'c5f8ca424772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banner',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('link_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_label',
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.Column('label_name', sa.String(length=20), nullable=True),
    sa.Column('label_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('label_id')
    )
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.alter_column('data_title',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('data_author',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('data_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('data_link',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('data_image_url',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('data_type',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.alter_column('data_type',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               existing_nullable=True)
        batch_op.alter_column('data_image_url',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               existing_nullable=True)
        batch_op.alter_column('data_link',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               existing_nullable=True)
        batch_op.alter_column('data_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('data_author',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               existing_nullable=True)
        batch_op.alter_column('data_title',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=255),
               existing_nullable=False)

    op.drop_table('data_label')
    op.drop_table('banner')
    # ### end Alembic commands ###
