"""empty message

Revision ID: a8191143b272
Revises: f8ae7a5d8574
Create Date: 2024-07-18 18:12:13.705214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8191143b272'
down_revision = 'f8ae7a5d8574'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_abstract', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data', schema=None) as batch_op:
        batch_op.drop_column('data_abstract')

    # ### end Alembic commands ###
